use_frameworks!

target 'NightNight_Example' do
  pod 'NightNight', :path => '../'

  target 'NightNight_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
